"""Machine-readable and human-readable reports for WaveForge runs."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable


def summarize(history: Iterable[dict]) -> dict[str, float]:
    """Aggregate numeric telemetry without requiring third-party packages."""
    rows = list(history)
    if not rows:
        return {"samples": 0, "delivery_rate_avg": 0.0, "latency_ms_avg": 0.0, "rssi_dbm_avg": 0.0}

    def avg(key: str) -> float:
        values = [float(row[key]) for row in rows if isinstance(row.get(key), (int, float))]
        return sum(values) / len(values) if values else 0.0

    return {
        "samples": len(rows),
        "delivery_rate_avg": avg("delivery_rate"),
        "latency_ms_avg": avg("avg_latency_ms"),
        "rssi_dbm_avg": avg("avg_rssi_dbm"),
    }


def write_json(history: Iterable[dict], path: str | Path) -> dict[str, float]:
    """Write raw samples plus an aggregate summary to a portable JSON file."""
    rows = list(history)
    payload = {"summary": summarize(rows), "samples": rows}
    Path(path).write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return payload["summary"]


def write_markdown(history: Iterable[dict], path: str | Path, title: str = "WaveForge Experiment Report") -> dict[str, float]:
    """Write a review-friendly Markdown report suitable for design reviews."""
    rows = list(history)
    summary = summarize(rows)
    lines = [
        f"# {title}", "", "## Summary", "",
        f"- Samples: {summary['samples']}",
        f"- Average delivery rate: {summary['delivery_rate_avg']:.2f}%",
        f"- Average latency: {summary['latency_ms_avg']:.3f} ms",
        f"- Average RSSI: {summary['rssi_dbm_avg']:.3f} dBm", "",
        "## Reproducibility", "",
        "Raw samples are generated by the deterministic WaveForge simulator; no physical radio interfaces are accessed.", "",
    ]
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return summary
